### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by zeynepgulhanuslu** [sweetcocoa/DeepComplexUNetPyTorch#1]
Hi,
First, thanks for sharing this code. I tried to train a model with my dataset. But it gave "Processing error!" and stop working. Could you please tell me what causes this error? 

Thanks.

**Comment by sweetcocoa** [comment]
Hi! Sorry for late reply. 

As long as I remember, That message is given by pypesq, when the function get weird signals. (for example, all-zero signals, or kindof that)

You can modify the source code of pypesq yourself(this is the way I did), or install latest version of [pypesq](https://github.com/vBaiCai/python-pesq/commit/0768cba738b3e044930e2d201c7c3705396433a2) (There are a bugfix 5 days ago).

**Comment by zeynepgulhanuslu** [comment]
Hi!

Not a problem, you don't have to be sorry:) Thank you for the explanation. You really helped me. 

Have a good day.
